#!/usr/bin/env bash

#### configure

# configure alias commands
config_alias() {
    file="$(pwd)/.bashrc"

    #cat $file | grep -v ^# | grep alias

    echo "alias sudo='sudo '" >> $file
    echo "alias ping='ping -c 3'" >> $file
    echo "alias ls='ls -ls --color=auto'" >> $file
    source $file
}

# configure bootloader (grub)
config_bootloader() {
    # change delay to 0 second
    sed -i 's/^GRUB_TIMEOUT=.*/GRUB_TIMEOUT=0/' /etc/default/grub
    update-grub
}

# configure firewall (IPtables)
config_firewall() {
    # Set default chain policies
    iptables -P INPUT DROP
    iptables -P FORWARD DROP
    iptables -P OUTPUT ACCEPT

    # Accept on localhost
    iptables -A INPUT -i lo -j ACCEPT
    iptables -A OUTPUT -o lo -j ACCEPT

    # Allow established sessions to receive traffic
    iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
}

#### security
# create admin user
# remove root access
# set bios password
# split partitions
# remove boot devices
# install security updates
# set grub password


#### clean-up

# remove foreign man files  
cleanup_manfiles() {
    rm -rf /usr/share/man/??
    rm -rf /usr/share/man/??_*
}

# remove unnecessary packages
#       apt autoremove
#       deborphan --guess-all


# install SSH (apt-get)
install_ssh() {

}

# install auto-reboot (cronjob)
schedule_reboot() {
    shutdown --reboot 10
}

# install auto-update (cronjob)
schedule_updates() {

}