#!/bin/bash
# Install Docker
## Remove old installations 
apt-get remove docker docker-engine docker.io containerd runc
apt-get autoremove
## Add docker repository
apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
## Install docker
apt-get update
apt-get install docker-ce docker-ce-cli containerd.io
## Add current user to docker group
usermod -aG docker $USER
