# Example to start a docker-compose file 
#   docker-compose -f template.yaml <up|down> [-d]

# Example to replace text in file 
#   sed -i 's/oldtext/newname/g' template.yaml

# Example to set environment variables
#   export "TRAEFIK_DOMAIN=your-domain.com"

# External links for additional information
#   - https://docs.docker.com/compose/environment-variables
#   - https://wiki.debian.org/EnvironmentVariables

version: "3.5"

services:
  ${DOCKER_SERVICE}:
    image: "${DOCKER_IMAGE}"
    container_name: "${DOCKER_SERVICE}"
    restart: unless-stopped
    networks: 
      - "${DOCKER_NETWORK}"
    volumes:
      - "${DOCKER_SERVICE}:/data"
#      - "/var/run/docker.sock:/var/run/docker.sock:ro"
#    ports:  
#      - "80:80/tcp"
#      - "443:443/tcp"
#    devices:  
#      - "/dev/ttyUSB0:/dev/ttyUSB0"
    labels: 
      - "traefik.enable=true" 
      - "traefik.docker.network=${DOCKER_NETWORK}" 
      - "traefik.http.routers.${DOCKER_SERVICE}.rule=Host(`${DOCKER_SERVICE}.${TRAEFIK_DOMAIN}`)" 
      - "traefik.http.routers.${DOCKER_SERVICE}.entrypoints=websecure" 
      - "traefik.http.routers.${DOCKER_SERVICE}.tls.certresolver=letsencrypt" 
      - "traefik.http.services.${DOCKER_SERVICE}.loadbalancer.server.port=${TRAEFIK_PORT}"
#      - "traefik.http.routers.portainer.middlewares=auth"    
#    environment:
#      - "MEM_LIMIT=1024M" 
#      - "TZ=<timezone>"
#      - "PUID=<puid>"
#      - "PGID=<pgid>"
#    depends_on:
#      - "<service-name>"

volumes:
  ${DOCKER_SERVICE}:  
    name: "${DOCKER_SERVICE}" 

networks:
  ${DOCKER_NETWORK}:  
    name: "${DOCKER_NETWORK}"
    external: true
#  ${DOCKER_SERVICE}:
#    name: "${DOCKER_SERVICE}"
#    external: false
