# Example to start a docker-compose file 
#   docker-compose -f template.yaml <up|down> [-d]

# Example to replace text in file 
#   sed -i 's/oldtext/newname/g' template.yaml

# Example to set environment variables
#   export "TRAEFIK_DOMAIN=your-domain.com"

# External links for additional information
#   - https://docs.docker.com/compose/environment-variables
#   - https://wiki.debian.org/EnvironmentVariables
#   - https://hub.docker.com/_/traefik
#   - https://doc.traefik.io/traefik/v2.0/

version: "3.5"

services:
  traefik:
    image: "traefik"
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--pilot.token=${TRAEFIK_TOKEN}"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      - "frontend"
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_PASS}"

volumes:
  letsencrypt:
    name: "letsencrypt"

networks:
  frontend:
    name: "frontend"
    external: false
