# To start a docker-compose file 
#    docker-compose -f template.yaml <up|down> [-d]

version: "3.5"

services:

  unifi:
    image: "ghcr.io/linuxserver/unifi-controller"
    container_name: "unifi"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.unifi.rule=Host(`unifi.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.unifi.entrypoints=websecure"
      - "traefik.http.routers.unifi.tls.certresolver=letsencrypt"
      - "traefik.http.services.unifi.loadbalancer.server.port=8443"
    networks:
      - "frontend"
    ports:
      - "8080:8080/tcp"  # required Device communication API
      - "3478:3478/udp"  # required STUN
      - "10001:10001/udp"  # required Device discovery
      - "8443:8443/tcp"  # required HTTPS front-end
#      - "8880:8880/tcp"  # optional HTTP front-end
#      - "1900:1900/udp"  # optional L2 discovery
#      - "5514:5514/tcp"  # optional Remote Syslog capture
#      - "6789:6789/tcp"  # optional Unifi mobile speed test
#      - "27117:27117/tcp"  # optional local-bound database communication
#      - "5656-5699/udp"  # optional AP-EDU broadcasting
    volumes:
      - "unifi:/config"
    environment:
      - "MEM_LIMIT=1024M" # limit memory use
#      - "TZ=<timezone>" # if else then UTC
#      - "PUID=<puid>" # runtime user ID
#      - "PGID=<pgid>" # runtime group ID


volumes:

  unifi:
    name: "unifi"


networks:

  frontend:
    name: "frontend"
    external: true
